---
title: 'Data & Scripts : Altitudinal zonation of green algae biodiversity in the French Alps'
author:
  - name: Adeline Stewart
    institute: pcv,lautaret,leca
  - name: Delphine Rioux
    institute: leca
  - name: Fréderic Boyer
    institute: leca
  - name: Ludovic Gielly
    institute: leca
  - name: François Pompanon
    institute: leca
  - name: Amélie Saillard
    institute: leca
  - name: Wilfried Thuiller
    institute: leca
  - name: The ORCHAMP Consortium 
  - name: Jean-Gabriel Valay
    institute: lautaret
  - name: Eric Maréchal
    email: eric.marechal@cea.fr
    institute: pcv
    correspondence: true
  - name: Eric Coissac
    institute: leca
    email: eric.coissac@metabarcoding.org 
    correspondence: true
institute:
  - pcv: Univ. Grenoble Alpes, CEA, CNRS, INRAE, IRIG, Laboratoire de Physiologie Cellulaire & Végétale, 38000 Grenoble.
  - lautaret: Univ. Grenoble-Alpes, CNRS, Jardin du Lautaret, 38000, Grenoble, France.
  - leca: Univ. Grenoble-Alpes, Univ. Savoie Mont Blanc, CNRS, LECA, 38000, Grenoble, France.
output:
  html_document:
    df_print: paged
    number_sections: yes
    pandoc_args:
      - '--lua-filter=style/scholarly-metadata.lua'
      - '--lua-filter=style/author-info-blocks.lua'
    css: style/splendor.css
  pdf_document: 
    number_sections: yes
    pandoc_args:
      - '--lua-filter=style/scholarly-metadata.lua'
      - '--lua-filter=style/author-info-blocks.lua'
---


# Github project

Every scripts and processed data are available from the Alpalga/Zonation github project.

  - https://github.com/Alpalga/Zonation
  
# Preprocessing of the raw data

The [`OBITools`](http://metabarcoding.org/obitools) commands used to preprocess
the dataz from the raw FASTQ files are described in the following bash script.

- [Bash script for the preprocessing of the raw data](obitools_preprocessing.sh) 

# Filtering of the data

- For the *Eukaryota* [`Euka03`](filtering_euka03.html) marker
- For the *Chlorophyta* [`Chlo01`](filtering_chlo01.html) marker
- For the *Chlorophyceae* [`Chlo02`](filtering_chlo02.html) marker

# Ecological analysis

Every code producing the presented results including the production
of the figures is available [here](alpin_algeaes.html)

# Processed data sets and results

Each processed dataset is composed of three coma separated values files (`.csv` files).

- For the *Eukaryota* `Euka03` marker
    + The MOTUs description file : [`Euka03.cleaned.motus.csv`](cleaned_datasets/Euka03.cleaned.motus.csv)
    + The samples description file : [`Euka03.cleaned.samples.csv`](cleaned_datasets/Euka03.cleaned.samples.csv)
    + The reads contengency table : [`Euka03.cleaned.reads.csv`](cleaned_datasets/Euka03.cleaned.reads.csv)
- For the *Chlorophyta* `Chlo01` marker
    + The MOTUs description file : [`Chlo01.cleaned.motus.csv`](cleaned_datasets/Chlo01.cleaned.motus.csv)
    + The samples description file : [`Chlo01.cleaned.samples.csv`](cleaned_datasets/Chlo01.cleaned.samples.csv)
    + The reads contengency table : [`Chlo01.cleaned.reads.csv`](cleaned_datasets/Chlo01.cleaned.reads.csv)
- For the *Chlorophyceae* `Chlo02` marker
    + The MOTUs description file : [`Chlo02.cleaned.motus.csv`](cleaned_datasets/Chlo02.cleaned.motus.csv)
    + The samples description file : [`Chlo02.cleaned.samples.csv`](cleaned_datasets/Chlo02.cleaned.samples.csv)
    + The reads contengency table : [`Chlo02.cleaned.reads.csv`](cleaned_datasets/Chlo02.cleaned.reads.csv)




